services:
  backend:
    image: c0dysharma/mern-backend:latest
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=employees
    ports:
      - 5050:5050
    networks:
      - mern-server
    depends_on:
      - mongodb

  frontend:
    image: c0dysharma/mern-frontend:latest
    environment:
      - VITE_BACKEND_URL=http://localhost:5050
    ports:
      - 5173:5173
    networks:
      - mern-server

  mongodb:
    image: mongo:latest
    networks:
      - mern-server
    volumes:
      - ~/deploy/mongo-data:/data/db

networks:
  mern-server:
    driver: bridge
