name: Node.js CI Backend

on:
  push:
    paths:
      - "mern/backend/**"

jobs:
  build:
    name: Build and test backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./mern/backend

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

  image:
    name: Build Image and push to Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Debug username
        run: echo "USERNAME=>>${{ secrets.DOCKER_USERNAME }}<< END"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./mern/backend
          file: ./mern/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: image # run after Docker image build
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # -----------------------------
      # Copy docker-compose.yml to server
      # -----------------------------
      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "~/deploy/"
          overwrite: true

      # -----------------------------
      # SSH into server and run docker-compose
      # -----------------------------
      - name: Run docker-compose on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/deploy
            docker-compose pull
            docker-compose up -d
